2024-10-03 13:26:24,144 - ERROR - error occured num must be an integer with 1 <= num <= 9, not 10
2024-10-05 12:42:36,762 - ERROR - error occured num must be an integer with 1 <= num <= 9, not 10
2024-10-06 11:51:59,853 - ERROR - error occured num must be an integer with 1 <= num <= 9, not 10
2024-10-06 12:25:02,447 - ERROR - error occured 'DataFrame' object has no attribute 'rest_index'
2024-10-06 12:32:13,276 - ERROR - Error during WOE transformation: "None of [Index(['CurrencyCode', 'ProviderId', 'ProductId', 'ProductCategory'], dtype='object')] are in the [columns]"
2024-10-06 12:35:21,729 - ERROR - Error during WOE transformation: The input feature(s) should be numeric type. Some of the input features                             has character values in it. Please use a encoder before performing monotonic operations.
2024-10-06 12:35:31,263 - ERROR - Error during WOE transformation: The input feature(s) should be numeric type. Some of the input features                             has character values in it. Please use a encoder before performing monotonic operations.
2024-10-06 12:35:31,268 - ERROR - error occurred "None of [Index(['ChannelId'], dtype='object')] are in the [columns]"
2024-10-06 12:35:34,917 - ERROR - Error during WOE transformation: The input feature(s) should be numeric type. Some of the input features                             has character values in it. Please use a encoder before performing monotonic operations.
2024-10-06 12:35:34,922 - ERROR - error occurred "None of [Index(['ChannelId'], dtype='object')] are in the [columns]"
2024-10-06 12:41:53,403 - ERROR - Error during WOE transformation: module 'pandas.core.algorithms' has no attribute 'quantile'
2024-10-06 12:42:49,384 - ERROR - Error during WOE transformation: The input feature(s) should be numeric type. Some of the input features                             has character values in it. Please use a encoder before performing monotonic operations.
2024-10-06 12:45:24,510 - ERROR - Error during WOE transformation: module 'pandas.core.algorithms' has no attribute 'quantile'
2024-10-06 12:47:50,427 - ERROR - Column CurrencyCode is not numeric. Converting...
2024-10-06 12:47:50,601 - ERROR - Column ProviderId is not numeric. Converting...
2024-10-06 12:47:50,752 - ERROR - Column ProductId is not numeric. Converting...
2024-10-06 12:47:50,919 - ERROR - Column ProductCategory is not numeric. Converting...
2024-10-06 12:47:51,712 - ERROR - Error during WOE transformation: 'ProviderId'
2024-10-06 12:50:55,678 - ERROR - Error during WOE transformation: module 'pandas.core.algorithms' has no attribute 'quantile'
2024-10-06 13:18:18,792 - ERROR - Error during WOE transformation: module 'pandas.core.algorithms' has no attribute 'quantile'
2024-10-06 13:18:19,091 - ERROR - error occured unsupported operand type(s) for -: 'Timestamp' and 'str'
2024-10-06 13:24:03,668 - ERROR - Error during WOE transformation: module 'pandas.core.algorithms' has no attribute 'quantile'
2024-10-06 13:24:04,418 - ERROR - error occured Cannot subtract tz-naive and tz-aware datetime-like objects
2024-10-06 13:28:08,223 - ERROR - Error during WOE transformation: module 'pandas.core.algorithms' has no attribute 'quantile'
2024-10-06 13:28:09,176 - ERROR - error occurred func is expected but received tuple in **kwargs.
2024-10-06 13:38:24,130 - ERROR - Error during WOE transformation: module 'pandas.core.algorithms' has no attribute 'quantile'
2024-10-06 13:38:25,062 - ERROR - Error in calculating WoE: func is expected but received tuple in **kwargs.
2024-10-06 13:40:33,695 - ERROR - Error during WOE transformation: module 'pandas.core.algorithms' has no attribute 'quantile'
2024-10-06 13:40:34,611 - ERROR - Error in calculating WoE: func is expected but received tuple in **kwargs.
2024-10-06 13:41:02,714 - ERROR - Error during WOE transformation: module 'pandas.core.algorithms' has no attribute 'quantile'
2024-10-06 13:41:03,297 - ERROR - Error in calculating WoE: func is expected but received tuple in **kwargs.
2024-10-06 13:41:31,044 - ERROR - Error in calculating WoE: func is expected but received tuple in **kwargs.
2024-10-07 11:28:12,996 - ERROR - Error during WOE transformation: module 'pandas.core.algorithms' has no attribute 'quantile'
2024-10-07 11:28:13,428 - ERROR - Error in calculating WoE: func is expected but received tuple in **kwargs.
2024-10-07 16:14:38,234 - ERROR - error occured could not convert string to float: 'TransactionId_1231'
2024-10-07 16:17:51,247 - ERROR - error occured could not convert string to float: 'ChannelId_3'
2024-10-07 16:18:29,497 - ERROR - Error occurred while preprocessing the data: "['ChannelId_3'] not found in axis"
2024-10-07 16:19:27,762 - ERROR - error occured could not convert string to float: 'ChannelId_3'
2024-10-07 16:22:14,044 - ERROR - error occured Cannot cast DatetimeArray to dtype float64
2024-10-07 16:23:46,160 - ERROR - error occured Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values
2024-10-07 16:32:17,830 - ERROR - error occured name 'X_test' is not defined
2024-10-07 16:33:04,663 - ERROR - error occured y should be a 1d array, got an array of shape (19133, 42) instead.
2024-10-07 23:38:45,771 - ERROR - error occured 
All the 60 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\bekib\Desktop\10ACADAMY\WEEK-SIX\week-6\.week-6\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\bekib\Desktop\10ACADAMY\WEEK-SIX\week-6\.week-6\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Users\bekib\Desktop\10ACADAMY\WEEK-SIX\week-6\.week-6\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\bekib\Desktop\10ACADAMY\WEEK-SIX\week-6\.week-6\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_estimators' parameter of RandomForestClassifier must be an int in the range [1, inf). Got '50,100,200' instead.

2024-10-07 23:38:45,771 - ERROR - error occured 
All the 60 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\bekib\Desktop\10ACADAMY\WEEK-SIX\week-6\.week-6\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\bekib\Desktop\10ACADAMY\WEEK-SIX\week-6\.week-6\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Users\bekib\Desktop\10ACADAMY\WEEK-SIX\week-6\.week-6\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\bekib\Desktop\10ACADAMY\WEEK-SIX\week-6\.week-6\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_estimators' parameter of RandomForestClassifier must be an int in the range [1, inf). Got '50,100,200' instead.

2024-10-08 15:45:19,950 - ERROR - Error executing pipeline: "['Label'] not found in axis"
2024-10-08 15:47:46,047 - ERROR - Error during WOE transformation: module 'pandas.core.algorithms' has no attribute 'quantile'
2024-10-08 15:47:46,423 - ERROR - Error in calculating WoE: func is expected but received tuple in **kwargs.
2024-10-08 19:43:28,502 - ERROR - Error during WOE transformation: module 'pandas.core.algorithms' has no attribute 'quantile'
2024-10-08 19:43:29,006 - ERROR - Error in calculating WoE: func is expected but received tuple in **kwargs.
